### PR TITLE
Etc hosts

### PR DESCRIPTION
**Pull request by moshevds**
I used te following commands to create this PR:

``` bash
$ git cherry-pick 1d441ae0 -n
$ git reset HEAD letsencrypt/auth_handler.py letsencrypt/tests/auth_handler_test.py
$ git checkout HEAD letsencrypt/auth_handler.py letsencrypt/tests/auth_handler_test.py
$ git cherry-pick 98f2d329 -n
$ git reset HEAD letsencrypt/auth_handler.py letsencrypt/tests/auth_handler_test.py
$ git checkout HEAD letsencrypt/auth_handler.py letsencrypt/tests/auth_handler_test.py
$ git commit -m "Adding required /etc/hosts entries to .travis.yml"
$ git cherry-pick f59dcc4b
```

The resets (and checkouts) are again to exclude the other files you edited.

### CODE REVIEW

**Comment by TheNavigat** [comment]
You should move this PR to https://github.com/letsencrypt/letsencrypt instead of my fork

**Comment by moshevds** [comment]
No, I wanted you to see this and decide about it. :-) It is your own code I pull-requested, you could forward it if you think it is worth it, but I don't want to stand on your toes if you don't.

**Comment by TheNavigat** [comment]
Ah, it looks perfect! :)

You can post the PR to https://github.com/letsencrypt/letsencrypt/. Thanks for the help!

**Comment by moshevds** [comment]
Okay, I'll do that.

**Pull request merged**
